version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_pessoas
    ports:
      - "5432:5432"
    restart: always
    networks:
      - api-cadastro-pessoa

  backend:
    container_name: backend
    image: alvescamila87/backend:1.0.0
    depends_on:
      - db
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres      
    networks:
      - api-cadastro-pessoa      

  frontend:
    container_name: frontend
    image: alvescamila87/frontend:1.0.0
    ports:
      - "3000:8080"
    depends_on:
      - backend
    networks:
      - api-cadastro-pessoa

networks:
  api-cadastro-pessoa:
    driver: bridge
