version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_pessoas
    ports:
      - "5432:5432"
    restart: always
    networks:
      - api-cadastro-pessoa

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    #image: alvescamila87/backend:1.0.0
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      #DATABASE_CONNECTION_URL: jdbc:postgresql://db:5432/db_pessoas
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      #SCOPE: dev
    networks:
      - api-cadastro-pessoa      

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#    image: alvescamila87/frontend:1.0.0
#    ports:
#      - "80:80"
#    depends_on:
#      - backend
#    networks:
#      - api-cadastro-pessoa

networks:
  api-cadastro-pessoa:
    driver: bridge
